### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by WilliamVenner**
Figured that it'd be nice to have a README

edit: also added LICENSE

### CODE REVIEW

**Comment by FPtje** [comment]
This fucks with subrepository cloning. I want one file and one file only. Sorry.

**Comment by WilliamVenner** [comment]
No problem, apologies, I didn't know.

**Comment by WilliamVenner** [comment]
You could always add it to another branch and add a link to that branch into mysqlite.lua?

**Comment by FPtje** [comment]
I'd rather have like wiki pages.

**Comment by WilliamVenner** [comment]
Done

**Pull request closed without merging**
